version: '3.8'

services:
  laravel:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    ports:
      - 8000:8000
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}

  react:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
