version: '3.8'

services:
  laravel:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    ports:
      - '8000:8000'
    networks:
      - app-network

  react:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
