version: '3.8'

services:
  laravel:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    ports:
      - '8000:8000'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:Jkcc2TAPYYP9VanmizCgnngOsMF0sZ3dpgZx8TcQ3Zw=
    networks:
      - app-network
    depends_on:
      - db

  react:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'ah_news'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
